version: '3'

services:
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app
      - db    

  app:
    build: 
      context: node  
    command: node index.js      
    container_name: app  
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network  
    tty: true  
    depends_on:
      - db  

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=FoxyL@dy51690714
      - MYSQL_USER=fsantaniello
      - MYSQL_PASSWORD=FoxyL@dy51690714
    networks:
      - node-network     

 
networks:
  node-network:
    driver: bridge
              